# Site settings
title: Vannet i Mjøsa
email: mathbra@stud.ntnu.no
url: https://ttk4850-g5.github.io/
description: "Informasjon om vannkvaliteten i Mjøsa"
keywords: "Beredskap, Vannmangel, Mjøsa, Drikkevann, Forurensing, Forsyningssikkerhet, Vanningsforbud, Kokevarsel, Vannberedskap, Badestatus, Samfunnssikkerhet"
skills: "STATUS: TRYGT"
meta_author: Gruppe5 TTK4850

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1c4892 #80B3FF
  #primary-rgb: "28,72,146" #"128,179,255"
  secondary: 030917 #FD6E8A
  secondary-dark: 030917 #A2122F

# Footer settings
footer:
  copyright: Gruppe 5
  location: Lokasjon
  social: Våre kontaktflater
  credits: Bratz-Queseth, Eikås, Hesselberg, Romøren og Valseth

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: school
    url: https://www.ntnu.no/oppdrag-mjosa
  - title: water-ladder
    url: https://www.imjosa.no/
  - title: house-flood-water
    url: https://www.hias.no/
  - title: caret-up
    url: https://www.sivilforsvaret.no/
  - title: clinic-medical
    url: https://www.sykehuset-innlandet.no/

# Postal address (add as many lines as necessary)
address:
  - line: NTNU
  - line: Mjøsa

# Credits content
credits: 'Denne nettsiden er en viderutvikling av temate Freelancer'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
